sudo: false
language: python
python:
- '3.6'
- 3.6-dev
- 3.7-dev
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
env:
  global:
  - secure: C1wPBGnK+aglece8TsXoWsdS3J+VY9l6krY8gqUu3GNLGW9p+yIxuEHeBJOXFuiqLa23ABKI9JZGCBlvUQLmqCaAA9cUoXm6DVjmyXsjKiI8gmcec1D1dehdyfrEYLUjhHso5rACZVVO4wu4rHe9h7etsLHUbIy2dYl4Iw1HUlKfhAf+mvtp46ztIZP3mv8yXvn0QRHqqs/US1QkXsYv/3AmveVxx+DfgHgohsKwhZfw67OEhrzMBoBCls0fZz3OQkq+p1b+tXHunUYEVrSXOhB4Xc4BE+zXWvoRE892293w+R9r2hL2s6AH3cnTlgiRwEtJrKQ4bje1hRtMxf+09A1XbNzsKauxCXgF8r77HbBVWLFJZ/9bf/wMLyDNi9F7rx2q9lfNsI22Ks1C2Ey++2yp75znXTTEufvOcBSdq+jdPcG4SYs7B3CHg8wei1gF1RY6O2CpUS/exCcy8xEU4sNu0Bm5heaIizFACZo1ylzC4zwlg/xvZD48nyO7ukENa/17CdMUStKZ0vFIBcnACcVwNtxV0uuTgqWIXuao0lchYX8Ww5riQQqppsQcR1juXPri+ZA63pDGJwXXavfqW5C7xpCmK4JisLl6wckReg7f7EAFnqxOM8fm2P6GKMVGR/YlN5qZQyvq8G/no/cWr70AKS6PmYPI4o2PsYuyGk0=
  - secure: vtEIsAly5llxaSHj+pT/92TVua84oBlAvKcOTVCiDdhXjqHFwyMqYpazNxtfszECptDoaYgCRPTeNPFp+sHsMTeuR7McMqYeJgFfGOsyTspr5YrUXMWLp3JB7JY8LELKoa4M6npYNIl0qGZ6uxm5wpjpNUVefG7ZXzSHyCxDk4SX/hupBeUJVoAD/Oh1PIX8aGHfXKNQlCXWUJs6xvhS9Z8p0y9EtfulNOFLBizd4JFopcFUMdmGpOcBAj/mKoIqcuMTGe9mmSl+xJ8ybCpArMVoXRw/UEJ7UU0IHWL8h9R+4vsPWcZ8FIo8mfJoufBXsB1xTdDKdBf9izbGnlmWU8mOd3jB37XPOBK6SUlBlbZefmlMXK4MCLrlP7W2rzlJAR+m7ol9itfWlorD0R6zz29Q+TfV6vG03uTmdpnco667U1OQJsqD+eOWWXeX8MPrW2iahIvynlaYid4ce5Frwci9V+uLuLpCzboY5gSuaxHiQ9ULGk7VoHEyzlxmLkuSeRInwL3vEn0vmrYmeJP0QyqMuEINheS1OBDdscKgbL96aM+kZbARQGz5hBPWsPF3t2WhAYJSU7x6GI0OIJbvZDrF0vqkccYA4k8mFFr4GY/GtlSmIY7AQUl+PxJZ/7swOebXHJKFVYclGgGje8daomg7iRYWMqIMbV0eBeCjzMg=
