
sudo: false
language: python
# command to install dependencies
install: "make"
# command to run tests
python:
    - "3.6"
    - "3.7"
install:
    - pip install -r requirements.txt
script:
    - python -m unittest test