
sudo: false
language: python
# command to install dependencies
python:
    - "3.6"
    - "3.6-dev"  # 3.6 development branch
    - "3.7-dev"  # 3.7 development branch
install:
    - pip install -r requirements.txt
script:
    - cd /home/travis/build/NashMiao/ontology-python-sdk/test
    - python -m unittest discover -s /home/travis/build/NashMiao/ontology-python-sdk/test -t /home/travis/build/NashMiao/ontology-python-sdk/test
