sudo: true
dist: xenial
language: python
python:
- '3.6'
- 3.6-dev
- '3.7'
- 3.7-dev
- 3.8-dev
cache: pip
env:
  global:
  - secure: hmihvVrUjcBdEYRF79/XXACDShn2kvkmcKzQgSo6M1UAbvnl+26WUiKiGc4nlgDJfY6WaEN8UasArWWvxN3rzpRygSPhmMjcV3aZsBhKuRgMy2spEM7K3Z4/VTVOqndo+MDjC1ke/vdSqlDnpc6yFWZK3Tci4gx0CAyyu0+MgPaysxfxOVuuyEZzj/3V6fPKKrVjJnJ042giMSuSW3IjZeZf5Yqo0NI+UGrrPU/pniyiaXS8OAL1MML7o+0iiGORJrcBfBAhAS67GrPhVR6EOFXWu03tZEl3MXTPRZ2WR6m+64ZOO+UKiW5lxAg1MTCbcJCvJsmbYD2RThRfH6/r0/nRbNiz5x2T+GAKgbFwL0wNZjaWAKiQzPVXMvEed9NlY7/YzqrPx8Q581DdCirx2jX4SgD4/rSiRZcbjEwfXTB9vQBO7DJwPAP5IAtBkpQr8tDZ12mtA7asPm5+8V2eqlwpuro/dYARAziKM821s+22GExyFpbHPpjrkWeYD7HMwXC+MPUFTJvLdZzQ38gjeMliK2+O89AzeKpfudJCt0J85aXSMqXH2LJ4iAdoHcm4t6L3wRjyns1R4i2NKop/MbA7pctUevDkrsh5+Pm5vmbZUcw4LB3PQZ1r/mDJJoq/ilPORnMCv65PmsYEKCd/vIuaEE/Z/4iB7qOnvSUkWqY=
  - secure: IV7CV9UrJa2cv1HlecgZljFcQ18Wo9jGN7X65vuhtFwtvfjreqKGQ/LRCXAIyOHziaoHy3CjhFUcdnAn5ihmbT5Wj4GeEnNmk+75df886UnoAikiXwJNcyRnS8jPu6JCHiF64kjsRpvpIcuWJaD+Qbnn/YSQFN5UMLvmQBsn0RsoWzisl2AP5dPqggB9TrLZSdmvbRuPmlox3GCZQpVvHwYYdmhlBfkevSFHI4aGjb8NPp3YmnW0cclhZwHnLz5wOce6H5LN91QTveiB9wq1vWluWCxxarfM9MbpuUC1Hs3c19Q78MiM7WRFmHuO9Fk2E233hORujhvhV6Z2R30p5r2t7kPOfeElwg73NQsCC6x0stvpZSJmneKIcbQdJoRqHWIyNHsLylHSrF+IsSGsAKiYFWb5caXUaVGZMiJbfC1URPheNZVtc93UXAWCqzKTSa6+hccJjEwLrxmZxzbKBoFUNoVZi7lt4rU5tAA9amUmgNjFcIivZjjsxVIR8Bh9f+sb4IGypi59HBTZVnS1Zu0ufKB/m+9y0dAXNLzzFFMfzX56w71e++DuCThJPeKf4duhJzeeoiusyXNYfN1f048+sjG1g5HLVPqfP2ITSQ428CkvQKwE6G0haCYk+qfmI+X0ugpsBR8w48Vardh2lc6fvMV/f0y3gfURKMN5BMk=
  - secure: Xvsl5k7IRZ5KOtVBjdFITxvZqxNIB8lx/UVoTYCLXOkY28Ql+9Igi9JV6UTTTQZpiPemhEEiLGrJyc+N3J/pFrI2ftdyK/gwdb6s1cwuuVAWe/cthrUyKPpEtnYusBfnFJyNCtm5x0BL/B1DARBRAUBO4dsnTJ4mwzAWiMpn4xQsYiZaLxhnY73hWRXHBd9xZbCH3ujU7PuaGzHWkClJPaWuVZD+FT/JYdLgAICY+tXSb/gHkFimwCMHHOhzA3M7vtpUUQwF1W81RY3cvyAFOZskDehP13ZDe74EVTn+MTckj4AUq/QpSXelTs1QstZtRP5O3atWVZ9kbLwnV5Hrn22ndu5o+Z8y4ZlsrFoMdymBU1D8uVuhHVEDZesnxl90ulpDCav/e668KNLOmnvxiY6k4FdfsyyS2Of1WmD+/3AxBpL8Hnhp1irMQyZvs2JRH+tTYTlM4iFo32uNPM5ZsI0fFCF8RPjx2bxGzkO+b4FvxhhMmgGEUUcW4bOiOzD4a3nAG3RZzb2+5Qn9r7sFGUb2Yv4LN6ukFWw3bYR09CuiKR+mwmsBa5akBrOZ+cSn1cXexFF8mobRpCGM/P93IvsbzVp7/pHH4g0vM1w1U7H+0MU83SbDW0YUzgoXPTcCCl3ErJXtwtgqcMgLL3Uph8czSbExXMvVsHfzTup+UDk=
install:
- make install
- sudo apt-get install build-essential
- sudo apt install wget
- sudo apt install unzip
- wget https://github.com/ontio/ontology/releases/download/v1.6.0/tool-linux.zip --no-check-certificate
- unzip tool-linux.zip
- "./tool-linux/sigsvr-linux-amd64 --abi ./tool-linux/abi &"
script:
- make test
- make coverage
- make build
deploy:
  provider: pypi
  user: NashMiao
  password:
    secure: kI22zgh0F7CZr1CMjB33BTIqfpRQBxdIsTchxdR3Ooq0LBCwp7RKL5F7Ijdc0SuK7pYsZT3t5UUBiltJLvjw+bxVegcqSHXvzN+LibEJZMagM2RujBADbNgai1xBUkcjfoDtiEKvPoJh8CQndjfOQgAQ6O97Y2o0kBS7ryLsHX+2ytUKhS/GSOSLw1sdlH3PIxCinzruLrMecgZgkUDxe6Co6N+l3IUklaOeqcANv9SobWAuNWS6ZdKD8e4gWZrmgxSVb/+CXnk0OfR2JB+w28xMSXrTS4hNdw+OVtefnuSmgKRCfJu2tiYXRG7aUQPHWnBnFZNdwjgK2puYdHUIDUsQ6wI1k4FrOIP3DDZPQ1RMCPI59l+lr9FG7wWjD/wKmtneYlT8VMz7GWKLDJjyeZwdWAt3kYeALQOG0a2eWwlf9yKcc4x+cKI6pOb9IkO8t4Uy0mwova/ztWeHhXbptL2othYDvlnfB9pIiDZYQUdHrdd3r9y9vK0BoE2xJ/f9xRfN1QCx0cJZpq797POHlL3NQgXKX3yRL8aYwYuHWWdjleZjajFRzyY2cfzKDgZGgSOKwAGzKHVJQhY4eX25tX9onl/37xua3glmQONHObRgqHRBgIgALy527LgxGD5j0gLhatC8A+IBtg8PUG8tlxaMEi5tPbQpO5/bGJlCEc4=
  on:
    python: 3.7
    brance: master
    tags: true
