sudo: true
language: python
python:
  - 3.6
  - 3.6-dev
  - 3.7-dev
env:
  global:
  - secure: hmihvVrUjcBdEYRF79/XXACDShn2kvkmcKzQgSo6M1UAbvnl+26WUiKiGc4nlgDJfY6WaEN8UasArWWvxN3rzpRygSPhmMjcV3aZsBhKuRgMy2spEM7K3Z4/VTVOqndo+MDjC1ke/vdSqlDnpc6yFWZK3Tci4gx0CAyyu0+MgPaysxfxOVuuyEZzj/3V6fPKKrVjJnJ042giMSuSW3IjZeZf5Yqo0NI+UGrrPU/pniyiaXS8OAL1MML7o+0iiGORJrcBfBAhAS67GrPhVR6EOFXWu03tZEl3MXTPRZ2WR6m+64ZOO+UKiW5lxAg1MTCbcJCvJsmbYD2RThRfH6/r0/nRbNiz5x2T+GAKgbFwL0wNZjaWAKiQzPVXMvEed9NlY7/YzqrPx8Q581DdCirx2jX4SgD4/rSiRZcbjEwfXTB9vQBO7DJwPAP5IAtBkpQr8tDZ12mtA7asPm5+8V2eqlwpuro/dYARAziKM821s+22GExyFpbHPpjrkWeYD7HMwXC+MPUFTJvLdZzQ38gjeMliK2+O89AzeKpfudJCt0J85aXSMqXH2LJ4iAdoHcm4t6L3wRjyns1R4i2NKop/MbA7pctUevDkrsh5+Pm5vmbZUcw4LB3PQZ1r/mDJJoq/ilPORnMCv65PmsYEKCd/vIuaEE/Z/4iB7qOnvSUkWqY=
go_import_path: github.com/ontio/ontology
install:
  - pip install -r requirements.txt
  - sudo apt install wget
  - sudo apt install unzip
  - wget https://github.com/ontio/ontology/releases/download/v1.6.0/tool-linux.zip --no-check-certificate
  - unzip tool-linux.zip
  - ./tool-linux/sigsvr-linux-amd64
script:
  - python -m unittest discover
